### PR TITLE
Add docker-compose for running dependent services and project

### PR DESCRIPTION
**Pull request by tetriscode**
# stream-registry PR

Add docker-compose for development and testing deployment. It does require that the container be pre built prior to running. 

### Added
* docker-compose.yml

# PR Checklist Forms

- [x] CHANGELOG.md updated
- [ ] Reviewer assigned
- [ ] PR assigned (presumably to submitter)
- [ ] Labels added (enhancement, bug, documentation)

### CODE REVIEW

**Comment by tetriscode** [comment]
I am not able to add labels or assign a reviewer.

**Comment by cricket007** [comment]
Bump? @nahguam @teabot

**Comment by nahguam** [comment]
In its current form, Stream Registry does not produce a docker image. Out of the box it has only 'default' configuration types. Expedia has handlers for internal business rules which we hope to eventually open source along with other components in the platform. At that point it would make sense to provide a solution like this so a developer would able to spin up a whole platform for debugging and testing.

**Comment by cricket007** [comment]
> In its current form, Stream Registry does not produce a docker image 

I added that... 

https://github.com/ExpediaGroup/stream-registry/blob/master/app/pom.xml#L48

**Pull request closed without merging**
